(defpackage #:3dmath
  (:use #:cl)
  (:export
   #:make-vec2
   #:make-vec3
   #:make-vec4
   #:vec-x
   #:vec-y
   #:vec-z
   #:vec-w
   #:vec2-sqlength
   #:vec3-sqlength
   #:vec4-sqlength
   #:vec2-sub
   #:vec3-sub
   #:vec4-sub
   #:vec2-length
   #:vec3-length
   #:vec4-length
   #:vec2-distance
   #:vec3-distance
   #:vec4-distance
   #:vec2-scale
   #:vec3-scale
   #:vec4-scale
   #:vec2-normalize
   #:vec3-normalize
   #:vec4-normalize
   #:vec2-projection
   #:vec3-projection
   #:vec4-projection
   #:vec4-scale
   #:vec2-equal
   #:vec3-equal
   #:vec4-equal
   #:vec2-add
   #:vec3-add
   #:vec4-add
   #:vec2-dot
   #:vec3-dot
   #:vec4-dot
   #:vec3-cross))
